# -*- coding: utf-8 -*-
"""sematic_search.pynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nA9E2xxzCVlBDQNe15B5Lc5BsU_QDH9x
"""

import json
import difflib
from sentence_transformers import SentenceTransformer, util

with open("drivers_v2.json") as f:
    drivers = json.load(f)

names_by_id = {d["id"]: d["name"] for d in drivers}
ids = [d["id"] for d in drivers]
corpus = [d["vibe_embedding_text"] for d in drivers]

model = SentenceTransformer("all-MiniLM-L6-v2")
doc_embeddings = model.encode(corpus, convert_to_tensor=True)

FUZZY_THRESHOLD = 0.75
KEYWORD_BOOST = 0.6
NATIONALITY_BOOST = 0.35  # smaller than KEYWORD_BOOST -- nationality alone is a
                          # weaker signal than an exact meme/nickname match,
                          # since many drivers can share a country
CONFIDENCE_FLOOR = 0.30  # below this, we say "no confident match" rather than guess

# Demonym -> country name, matching whatever string is used in each driver's
# "country" field. Extend this as you add drivers from new countries.
DEMONYMS = {
    "dutch": "Netherlands",
    "british": "United Kingdom",
    "english": "United Kingdom",
    "german": "Germany",
    "finnish": "Finland",
    "finn": "Finland",
    "spanish": "Spain",
    "australian": "Australia",
    "mexican": "Mexico",
    "brazilian": "Brazil",
    "french": "France",
    "monegasque": "Monaco",
    "canadian": "Canada",
    "italian": "Italy",
}


def curated_terms(driver):
    terms = []
    terms += driver.get("memes", [])
    terms += driver.get("aliases", [])
    terms += driver.get("nicknames", [])
    terms += driver.get("search_keywords", [])
    return terms


def nationality_match(query, driver_country):
    """Return True if the query contains a demonym matching this driver's country."""
    query_lower = query.lower()
    for demonym, country in DEMONYMS.items():
        if demonym in query_lower and country == driver_country:
            return True
    return False


def best_fuzzy_match(query, terms):
    query = query.lower().strip()
    best = 0.0
    for term in terms:
        ratio = difflib.SequenceMatcher(None, query, term.lower().strip()).ratio()
        best = max(best, ratio)
    return best


def hybrid_rank(query):
    query_embedding = model.encode(query, convert_to_tensor=True)
    embed_scores = util.cos_sim(query_embedding, doc_embeddings)[0].tolist()

    results = []
    for i, driver in enumerate(drivers):
        embed_score = embed_scores[i]
        fuzzy_score = best_fuzzy_match(query, curated_terms(driver))
        keyword_boost = KEYWORD_BOOST if fuzzy_score >= FUZZY_THRESHOLD else 0.0
        nat_boost = NATIONALITY_BOOST if nationality_match(query, driver.get("country", "")) else 0.0
        results.append((driver["id"], embed_score + keyword_boost + nat_boost))

    results.sort(key=lambda x: x[1], reverse=True)
    return results


# ---------------------------------------------------------------------------
# LABELED TEST SET
# Format: (query, expected_driver_id_or_None)
# None means: "no single driver should confidently win this."
# ---------------------------------------------------------------------------
TEST_SET = [
    # --- Easy exact meme/nickname matches ---
    ("bwoah", "kimi_raikkonen"),
    ("shoey", "daniel_ricciardo"),
    ("simply lovely", "max_verstappen"),
    ("hammer time", "lewis_hamilton"),
    ("smooth operator", "carlos_sainz"),
    ("mr saturday", "george_russell"),
    ("checo", "sergio_perez"),
    ("to whom it may concern", "valtteri_bottas"),
    # NOTE: "The Professor" is genuinely shared by Rosberg and Prost in this
    # dataset -- not testable as a clean single-answer case. Left out on
    # purpose rather than forcing a fake "correct" answer.
    ("multi 21", "sebastian_vettel"),
    ("honey badger", "daniel_ricciardo"),
    ("el plan", "fernando_alonso"),
    ("gp2 engine", "fernando_alonso"),
    ("looks good", "oscar_piastri"),  # relies on embedding fallback, not a curated term
    ("inchident", "max_verstappen"),

    # --- Paraphrases, no exact meme wording ---
    ("cold emotionless quiet driver", "kimi_raikkonen"),
    ("driver who loves ice cream and hates interviews", "kimi_raikkonen"),
    ("driver obsessed with defensive driving", "fernando_alonso"),
    ("driver who celebrates by drinking from his shoe", "daniel_ricciardo"),
    ("aggressive dutch champion", "max_verstappen"),
    ("british driver who retired right after winning a title", "nico_rosberg"),
    ("driver known for a distinctive mullet", "valtteri_bottas"),
    ("driver nicknamed after a fierce jungle animal", "daniel_ricciardo"),

    # --- Nonsense / should NOT confidently match anyone ---
    ("banana bogaloo jump", None),
    ("purple elephant racing", None),
    ("spaghetti tuesday grand prix", None),
    ("my grandmother's garden fence", None),

    # --- Team/ambiguous-level queries that shouldn't cleanly resolve to one person ---
    ("masterplan", None),
    ("team strategy mistake", None),
]


def run_eval():
    passed = 0
    failed_cases = []

    for query, expected_id in TEST_SET:
        ranking = hybrid_rank(query)
        top_id, top_score = ranking[0]

        if expected_id is None:
            ok = top_score < CONFIDENCE_FLOOR
        else:
            ok = (top_id == expected_id)

        if ok:
            passed += 1
        else:
            failed_cases.append((query, expected_id, top_id, top_score, ranking[:3]))

    total = len(TEST_SET)
    accuracy = passed / total * 100

    print(f"\n{'='*60}")
    print(f"RESULTS: {passed}/{total} passed  ({accuracy:.1f}% accuracy)")
    print(f"{'='*60}\n")

    if failed_cases:
        print("FAILED CASES:\n")
        for query, expected_id, top_id, top_score, top3 in failed_cases:
            expected_name = names_by_id.get(expected_id, "NOBODY (expected low confidence)")
            got_name = names_by_id.get(top_id, top_id)
            print(f"Query: '{query}'")
            print(f"  expected: {expected_name}")
            print(f"  got:      {got_name}  (score={top_score:.4f})")
            print(f"  top 3:    " + ", ".join(f"{names_by_id[i]}={s:.3f}" for i, s in top3))
            print()
    else:
        print("All test cases passed.")


if __name__ == "__main__":
    run_eval()

"""# fine tuned model"""

import json
from sentence_transformers import SentenceTransformer, InputExample, losses
from torch.utils.data import DataLoader

with open("drivers_v2.json") as f:
    drivers = json.load(f)

id_to_vibe_text = {d["id"]: d["vibe_embedding_text"] for d in drivers}

model = SentenceTransformer("all-MiniLM-L6-v2")

train_examples = []

# --- Source 1: auto-generated pairs from curated fields (free, no new labeling) ---
for d in drivers:
    positive_text = d["vibe_embedding_text"]
    curated_terms = (
        d.get("memes", [])
        + d.get("aliases", [])
        + d.get("nicknames", [])
        + d.get("search_keywords", [])
    )
    for term in curated_terms:
        train_examples.append(InputExample(texts=[term, positive_text]))

# --- Source 2: hand-written paraphrase pairs, DELIBERATELY different wording
#     from batch_eval.py's TEST_SET, to avoid contaminating the eval set ---
paraphrase_training_pairs = [
    ("emotionless finnish racer who avoids the media", "kimi_raikkonen"),
    ("driver who barely talks to journalists", "kimi_raikkonen"),
    ("aggressive defensive spanish veteran", "fernando_alonso"),
    ("driver who parties by drinking from his own shoe", "daniel_ricciardo"),
    ("hyper competitive dutch racer known for outbursts", "max_verstappen"),
    ("perfectionist calm mercedes legend", "lewis_hamilton"),
    ("honest self critical monaco based driver", "charles_leclerc"),
    ("calm consistent spanish strategist who loves spicy food", "carlos_sainz"),
    ("funny streamer mclaren driver who plays video games", "lando_norris"),
    ("unbothered rookie compared to an emotionless legend", "oscar_piastri"),
    ("methodical british qualifier who prepares detailed arguments", "george_russell"),
    ("humble german driver who protects bees", "sebastian_vettel"),
    ("patient reliable mexican racer great at saving tyres", "sergio_perez"),
    ("blunt finnish driver with a mullet who loves coffee", "valtteri_bottas"),
    ("driver who unexpectedly quit right after winning his title", "nico_rosberg"),
    ("relaxed champion who mastered wet weather driving", "jenson_button"),
    ("relentless dominant german legend with a strong work ethic", "michael_schumacher"),
    ("intense brazilian legend famous in the rain", "ayrton_senna"),
    ("calculated strategic french champion nicknamed the professor", "alain_prost"),
    ("quiet fast respectful finnish champion", "mika_hakkinen"),
    ("unlucky honest german driver who never got a podium", "nico_hulkenberg"),
    ("emotional resilient french driver who bounced back", "pierre_gasly"),
    ("loyal brazilian driver who always finished second", "rubens_barrichello"),
    ("son of a racing legend who became a british champion himself", "damon_hill"),
    ("outspoken canadian son of a famous racer", "jacques_villeneuve"),
    ("fearless mustached british champion", "nigel_mansell"),
]

for query_text, driver_id in paraphrase_training_pairs:
    train_examples.append(InputExample(texts=[query_text, id_to_vibe_text[driver_id]]))

print(f"Total training pairs: {len(train_examples)}")

train_dataloader = DataLoader(train_examples, shuffle=True, batch_size=16)
train_loss = losses.MultipleNegativesRankingLoss(model)

model.fit(
    train_objectives=[(train_dataloader, train_loss)],
    epochs=4,
    warmup_steps=10,
    show_progress_bar=True,
)

model.save("f1_finetuned_model")
print("\nSaved fine-tuned model to ./f1_finetuned_model/")
print("Download this folder from Colab's file panel if you want to keep it,")
print("or just keep using it within the same Colab session for evaluation.")

"""# Fine tuned batch eval

"""

"""
BATCH EVALUATION: run a labeled test set through the hybrid search pipeline
and report top-1 accuracy, instead of eyeballing queries one at a time.

Run this the same way as the other real-embedding scripts (Google Colab or
locally with sentence-transformers installed) -- needs internet to download
the model. Put this file + drivers_v2.json in the same folder/session.

WHAT COUNTS AS A "PASS":
  For a labeled query, the #1 ranked driver must match the expected driver id.
  For a query expected to match NOBODY (nonsense, ambiguous team-level memes),
  the top score must fall below a "confidence floor" -- i.e. the system
  correctly stays unsure rather than confidently picking a wrong answer.

HOW TO EXTEND THIS:
  Add more (query, expected_id) pairs to TEST_SET below as you find new
  cases worth locking in -- especially ones you previously found broken,
  so they can never silently regress again.
"""

import json
import difflib
from sentence_transformers import SentenceTransformer, util

with open("drivers_v2.json") as f:
    drivers = json.load(f)

names_by_id = {d["id"]: d["name"] for d in drivers}
ids = [d["id"] for d in drivers]
corpus = [d["vibe_embedding_text"] for d in drivers]

model = SentenceTransformer("f1_finetuned_model")  # load the fine-tuned model, not the base one
doc_embeddings = model.encode(corpus, convert_to_tensor=True)

FUZZY_THRESHOLD = 0.75
KEYWORD_BOOST = 0.6
NATIONALITY_BOOST = 0.35  # smaller than KEYWORD_BOOST -- nationality alone is a
                          # weaker signal than an exact meme/nickname match,
                          # since many drivers can share a country
CONFIDENCE_FLOOR = 0.30  # below this, we say "no confident match" rather than guess

# Demonym -> country name, matching whatever string is used in each driver's
# "country" field. Extend this as you add drivers from new countries.
DEMONYMS = {
    "dutch": "Netherlands",
    "british": "United Kingdom",
    "english": "United Kingdom",
    "german": "Germany",
    "finnish": "Finland",
    "finn": "Finland",
    "spanish": "Spain",
    "australian": "Australia",
    "mexican": "Mexico",
    "brazilian": "Brazil",
    "french": "France",
    "monegasque": "Monaco",
    "canadian": "Canada",
    "italian": "Italy",
}


def curated_terms(driver):
    terms = []
    terms += driver.get("memes", [])
    terms += driver.get("aliases", [])
    terms += driver.get("nicknames", [])
    terms += driver.get("search_keywords", [])
    return terms


def nationality_match(query, driver_country):
    """Return True if the query contains a demonym matching this driver's country."""
    query_lower = query.lower()
    for demonym, country in DEMONYMS.items():
        if demonym in query_lower and country == driver_country:
            return True
    return False


def best_fuzzy_match(query, terms):
    query = query.lower().strip()
    best = 0.0
    for term in terms:
        ratio = difflib.SequenceMatcher(None, query, term.lower().strip()).ratio()
        best = max(best, ratio)
    return best


def hybrid_rank(query):
    query_embedding = model.encode(query, convert_to_tensor=True)
    embed_scores = util.cos_sim(query_embedding, doc_embeddings)[0].tolist()

    results = []
    for i, driver in enumerate(drivers):
        embed_score = embed_scores[i]
        fuzzy_score = best_fuzzy_match(query, curated_terms(driver))
        keyword_boost = KEYWORD_BOOST if fuzzy_score >= FUZZY_THRESHOLD else 0.0
        nat_boost = NATIONALITY_BOOST if nationality_match(query, driver.get("country", "")) else 0.0
        results.append((driver["id"], embed_score + keyword_boost + nat_boost))

    results.sort(key=lambda x: x[1], reverse=True)
    return results


# ---------------------------------------------------------------------------
# LABELED TEST SET
# Format: (query, expected_driver_id_or_None)
# None means: "no single driver should confidently win this."
# ---------------------------------------------------------------------------
TEST_SET = [
        ('bwoah', 'kimi_raikkonen'),
    ('el plan', 'fernando_alonso'),
    ('shoey', 'daniel_ricciardo'),
    ('simply lovely', 'max_verstappen'),
    ('hammer time', 'lewis_hamilton'),
    ('we are checking', 'charles_leclerc'),
    ('smooth operator', 'carlos_sainz'),
    ('quadrant', 'lando_norris'),
    ("webber's student", 'oscar_piastri'),
    ('safety car crash', 'george_russell'),
    ('multi 21', 'sebastian_vettel'),
    ('street circuit specialist', 'sergio_perez'),
    ('mullet', 'valtteri_bottas'),
    ('retired immediately', 'nico_rosberg'),
    ('smooth driver', 'jenson_button'),
    ('ferrari legend', 'michael_schumacher'),
    ('monaco king', 'ayrton_senna'),
    ('calculated driver', 'alain_prost'),
    ('flying finn', 'mika_hakkinen'),
    ('no podium', 'nico_hulkenberg'),
    ('monza miracle', 'pierre_gasly'),
    ('forever second', 'rubens_barrichello'),
    ('son of graham hill', 'damon_hill'),
    ('fearless overtakes', 'jacques_villeneuve'),
    ('the lion', 'nigel_mansell'),
    ('mercedes wonderkid', 'kimi_antonelli'),
    ('mazespin', 'nikita_mazepin'),
    ('brazil is back', 'gabriel_bortoleto'),
    ('they race me so hard', 'alex_albon'),
    ('always fighting teammates', 'esteban_ocon'),
    ('angry team radio', 'yuki_tsunoda'),
    ('suck my balls', 'kevin_magnussen'),
    ('fireball crash', 'romain_grosjean'),
    ("michael's son", 'mick_schumacher'),
    ('wet weather specialist', 'lance_stroll'),
    ('first chinese f1 driver', 'zhou_guanyu'),
    ('american hope', 'logan_sargeant'),
    ('one race wonder', 'nyck_de_vries'),
    ('long hair', 'antonio_giovinazzi'),
    ('last lap divebombs', 'kamui_kobayashi'),
    ('torpedo', 'daniil_kvyat'),
    ('formula e king', 'jean_eric_vergne'),
    ('le mans champion', 'brendon_hartley'),
    ('destroyed by alonso', 'stoffel_vandoorne'),
    ('saved sauber', 'felipe_nasr'),
    ('wehrlein', 'pascal_wehrlein'),
    ('i think ericsson hit us', 'marcus_ericsson'),
    ('monaco 2008', 'adrian_sutil'),
    ('sky sports commentator', 'paul_di_resta'),
    ('underrated finn', 'heikki_kovalainen'),
    ('trulli train', 'jarno_trulli'),
    ('is that glock?', 'timo_glock'),
    ('most podiums without a win', 'nick_heidfeld'),
    ('spa 2009', 'giancarlo_fisichella'),
    ('what if', 'robert_kubica'),
    ('crashdonado', 'pastor_maldonado'),
    ('abu dhabi 2010', 'vitaly_petrov'),
    ('formula e', 'jerome_dambrosio'),
    ('first indian formula one driver', 'narain_karthikeyan'),
    ('mclaren test driver', 'pedro_de_la_rosa'),
    ('senna nephew', 'bruno_senna'),
    ('formula e legend', 'lucas_di_grassi'),
    ('sky sports analyst', 'karun_chandhok'),
    ('unexpected substitute', 'sakon_yamamoto'),
    ('ferrari cult hero', 'jean_alesi'),
    ('prankster', 'gerhard_berger'),
    ('1999 title contender', 'heinz_harald_frentzen'),
    ('reliable finn', 'mika_salo'),
    ('underdog winner', 'johnny_herbert'),
    ('monaco 1996', 'olivier_panis'),
    ('longevity', 'ricardo_patrese'),
    ('1985 title fight', 'michele_alboreto'),
    ('leyton house miracle', 'ivan_capelli'),
    ('mountaineer', 'ukyo_katayama'),
    ('father of max verstappen', 'jos_verstappen'),
    ('portuguese pioneer', 'pedro_lamy'),
    ('long-time ferrari test driver', 'luca_badoer'),
    ('cart legend', 'alessandro_zanardi'),
    ('footwork podium', 'gianni_morbidelli'),
    ('youngest f2 race winner', 'arvid_lindblad'),
    ('unlucky career', 'theo_pourchaire'),
    ('aston martin reserve', 'felipe_drugovich'),
    ('almost made f1', 'frederik_vesti'),
    ('alpine junior', 'victor_martins'),
    ('american racing legend', 'mario_andretti'),
    ('last ferrari champion until schumacher', 'jody_scheckter'),
    ('hard racer', 'alan_jones'),
    ('first american-born champion', 'phil_hill'),
    ('built his own championship car', 'jack_brabham'),
    ('natural talent', 'jim_clark'),
    ('triple crown', 'graham_hill'),
    ('motorcycle champion', 'john_surtees'),
    ('only posthumous champion', 'jochen_rindt'),
    ('no fear', 'gilles_villeneuve'),

]


def run_eval():
    passed = 0
    failed_cases = []

    for query, expected_id in TEST_SET:
        ranking = hybrid_rank(query)
        top_id, top_score = ranking[0]

        if expected_id is None:
            ok = top_score < CONFIDENCE_FLOOR
        else:
            ok = (top_id == expected_id)

        if ok:
            passed += 1
        else:
            failed_cases.append((query, expected_id, top_id, top_score, ranking[:3]))

    total = len(TEST_SET)
    accuracy = passed / total * 100

    print(f"\n{'='*60}")
    print(f"RESULTS: {passed}/{total} passed  ({accuracy:.1f}% accuracy)")
    print(f"{'='*60}\n")

    if failed_cases:
        print("FAILED CASES:\n")
        for query, expected_id, top_id, top_score, top3 in failed_cases:
            expected_name = names_by_id.get(expected_id, "NOBODY (expected low confidence)")
            got_name = names_by_id.get(top_id, top_id)
            print(f"Query: '{query}'")
            print(f"  expected: {expected_name}")
            print(f"  got:      {got_name}  (score={top_score:.4f})")
            print(f"  top 3:    " + ", ".join(f"{names_by_id[i]}={s:.3f}" for i, s in top3))
            print()
    else:
        print("All test cases passed.")


if __name__ == "__main__":
    run_eval()

"""# novel stress test"""

"""
BATCH EVALUATION: run a labeled test set through the hybrid search pipeline
and report top-1 accuracy, instead of eyeballing queries one at a time.

Run this the same way as the other real-embedding scripts (Google Colab or
locally with sentence-transformers installed) -- needs internet to download
the model. Put this file + drivers_v2.json in the same folder/session.

WHAT COUNTS AS A "PASS":
  For a labeled query, the #1 ranked driver must match the expected driver id.
  For a query expected to match NOBODY (nonsense, ambiguous team-level memes),
  the top score must fall below a "confidence floor" -- i.e. the system
  correctly stays unsure rather than confidently picking a wrong answer.

HOW TO EXTEND THIS:
  Add more (query, expected_id) pairs to TEST_SET below as you find new
  cases worth locking in -- especially ones you previously found broken,
  so they can never silently regress again.
"""

import json
import difflib
from sentence_transformers import SentenceTransformer, util

with open("drivers_v2.json") as f:
    drivers = json.load(f)

names_by_id = {d["id"]: d["name"] for d in drivers}
ids = [d["id"] for d in drivers]
corpus = [d["vibe_embedding_text"] for d in drivers]

model = SentenceTransformer("f1_finetuned_model")  # load the fine-tuned model, not the base one
doc_embeddings = model.encode(corpus, convert_to_tensor=True)

FUZZY_THRESHOLD = 0.75
KEYWORD_BOOST = 0.6
NATIONALITY_BOOST = 0.35  # smaller than KEYWORD_BOOST -- nationality alone is a
                          # weaker signal than an exact meme/nickname match,
                          # since many drivers can share a country
CONFIDENCE_FLOOR = 0.30  # below this, we say "no confident match" rather than guess

# Demonym -> country name, matching whatever string is used in each driver's
# "country" field. Extend this as you add drivers from new countries.
DEMONYMS = {
    "dutch": "Netherlands",
    "british": "United Kingdom",
    "english": "United Kingdom",
    "german": "Germany",
    "finnish": "Finland",
    "finn": "Finland",
    "spanish": "Spain",
    "australian": "Australia",
    "mexican": "Mexico",
    "brazilian": "Brazil",
    "french": "France",
    "monegasque": "Monaco",
    "canadian": "Canada",
    "italian": "Italy",
}


def curated_terms(driver):
    terms = []
    terms += driver.get("memes", [])
    terms += driver.get("aliases", [])
    terms += driver.get("nicknames", [])
    terms += driver.get("search_keywords", [])
    return terms


def nationality_match(query, driver_country):
    """Return True if the query contains a demonym matching this driver's country."""
    query_lower = query.lower()
    for demonym, country in DEMONYMS.items():
        if demonym in query_lower and country == driver_country:
            return True
    return False


def best_fuzzy_match(query, terms):
    query = query.lower().strip()
    best = 0.0
    for term in terms:
        ratio = difflib.SequenceMatcher(None, query, term.lower().strip()).ratio()
        best = max(best, ratio)
    return best


def hybrid_rank(query):
    query_embedding = model.encode(query, convert_to_tensor=True)
    embed_scores = util.cos_sim(query_embedding, doc_embeddings)[0].tolist()

    results = []
    for i, driver in enumerate(drivers):
        embed_score = embed_scores[i]
        fuzzy_score = best_fuzzy_match(query, curated_terms(driver))
        keyword_boost = KEYWORD_BOOST if fuzzy_score >= FUZZY_THRESHOLD else 0.0
        nat_boost = NATIONALITY_BOOST if nationality_match(query, driver.get("country", "")) else 0.0
        results.append((driver["id"], embed_score + keyword_boost + nat_boost))

    results.sort(key=lambda x: x[1], reverse=True)
    return results


# ---------------------------------------------------------------------------
# LABELED TEST SET
# Format: (query, expected_driver_id_or_None)
# None means: "no single driver should confidently win this."
# ---------------------------------------------------------------------------
TEST_SET = [
    # --- Easy exact meme/nickname matches ---
    ("bwoah", "kimi_raikkonen"),
    ("shoey", "daniel_ricciardo"),
    ("simply lovely", "max_verstappen"),
    ("hammer time", "lewis_hamilton"),
    ("smooth operator", "carlos_sainz"),
    ("mr saturday", "george_russell"),
    ("checo", "sergio_perez"),
    ("to whom it may concern", "valtteri_bottas"),
    # NOTE: "The Professor" is genuinely shared by Rosberg and Prost in this
    # dataset -- not testable as a clean single-answer case. Left out on
    # purpose rather than forcing a fake "correct" answer.
    ("multi 21", "sebastian_vettel"),
    ("honey badger", "daniel_ricciardo"),
    ("el plan", "fernando_alonso"),
    ("gp2 engine", "fernando_alonso"),
    ("looks good", "oscar_piastri"),  # relies on embedding fallback, not a curated term
    ("inchident", "max_verstappen"),

    # --- Paraphrases, no exact meme wording ---
    ("cold emotionless quiet driver", "kimi_raikkonen"),
    ("driver who loves ice cream and hates interviews", "kimi_raikkonen"),
    ("driver obsessed with defensive driving", "fernando_alonso"),
    ("driver who celebrates by drinking from his shoe", "daniel_ricciardo"),
    ("aggressive dutch champion", "max_verstappen"),
    ("driver who retired right after winning a title", "nico_rosberg"),  # FIXED: Rosberg is German/Finnish, not British - my earlier label was wrong
    ("driver known for a distinctive mullet", "valtteri_bottas"),
    ("driver nicknamed after a fierce jungle animal", "daniel_ricciardo"),

    # --- Nonsense / should NOT confidently match anyone ---
    ("banana bogaloo jump", None),
    ("purple elephant racing", None),
    ("spaghetti tuesday grand prix", None),
    ("my grandmother's garden fence", None),

    # --- Team/ambiguous-level queries that shouldn't cleanly resolve to one person ---
    ("masterplan", None),
    ("team strategy mistake", None),
]


def run_eval():
    passed = 0
    failed_cases = []

    for query, expected_id in TEST_SET:
        ranking = hybrid_rank(query)
        top_id, top_score = ranking[0]

        if expected_id is None:
            ok = top_score < CONFIDENCE_FLOOR
        else:
            ok = (top_id == expected_id)

        if ok:
            passed += 1
        else:
            failed_cases.append((query, expected_id, top_id, top_score, ranking[:3]))

    total = len(TEST_SET)
    accuracy = passed / total * 100

    print(f"\n{'='*60}")
    print(f"RESULTS: {passed}/{total} passed  ({accuracy:.1f}% accuracy)")
    print(f"{'='*60}\n")

    if failed_cases:
        print("FAILED CASES:\n")
        for query, expected_id, top_id, top_score, top3 in failed_cases:
            expected_name = names_by_id.get(expected_id, "NOBODY (expected low confidence)")
            got_name = names_by_id.get(top_id, top_id)
            print(f"Query: '{query}'")
            print(f"  expected: {expected_name}")
            print(f"  got:      {got_name}  (score={top_score:.4f})")
            print(f"  top 3:    " + ", ".join(f"{names_by_id[i]}={s:.3f}" for i, s in top3))
            print()
    else:
        print("All test cases passed.")


if __name__ == "__main__":
    run_eval()